{{- $fullName := include "chorus-ci.fullname" . -}}
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: {{ $fullName }}-default
  labels:
    {{- include "chorus-ci.labels" . | nindent 4 }}
spec:
  jetstream:
    version: {{ .Values.eventBus.jetstream.version }}
    replicas: 1
    {{- if .Values.eventBus.debug }}
    startArgs: ["-D"]
    {{- end }}
    streamConfig: |
      replicas: 1
