# Default values for argo-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environments:
  - name: chorus-build
    description: CHORUS build
    envRepoURL: https://github.com/qndn-dot/environment-template.git
    registryURL: harbor.build.chorus-tre.local
    cluster: chorus-build

  - name: chorus
    description: CHORUS
    envRepoURL: https://github.com/qndn-dot/environment-template.git
    registryURL: harbor.build.chorus-tre.local
    cluster: chorus